
version: '3'

services:
  email:
    build: email/
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'

  database:
      image: postgres
      environment: 
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: emails
      volumes:
        - ./data/db.backup.sql:/docker-entrypoint-initdb.d/db.backup.sql
